### Send POST request with json body
POST http://localhost:9218/essttp-stubs/eligibility/data
Content-Type: application/json

{
  "idType": "EMPREF",
  "idNumber": "AA12345678",
  "regimeType": "PAYE",
  "returnFinancials": true
}
