### Send POST request with json body
POST http://localhost:9218/time-to-pay/self-serve/eligibility
Content-Type: application/json

{
  "idType": "EMPREF",
  "idNumber": "AA12345678",
  "regimeType": "PAYE",
  "returnFinancials": true
}

### upload elegibility data with errors

POST http://localhost:9218/time-to-pay/self-serve/eligibility/paye/123AAAA
Content-Type: application/json

{
  "idType": "NI",
  "idNumber": "A00000000001",
  "regimeType": "PAYE",
  "processingDate": "2022-03-10",
  "customerDetails": {
    "country": "NI",
    "postCode": "B5 7LN"
  },
  "eligibilityStatus": {
    "overallEligibilityStatus": false,
    "minPlanLengthMonths": 1,
    "maxPlanLengthMonths": 6
  },
  "eligibilityRules": {
    "hasRlsOnAddress": true,
    "rlsReason": "Receiver is not known",
    "markedAsInsolvent": true,
    "isLessThanMinDebtAllowance": false,
    "isMoreThanMaxDebtAllowance": false,
    "disallowedChargeLocks": false,
    "existingTTP": false,
    "minInstalmentAmount": 300,
    "maxInstalmentAmount": 600,
    "exceedsMaxDebtAge": false,
    "eligibleChargeType": false,
    "missingFiledReturns": false
  },
  "financialLimitBreached": {
    "status": true,
    "calculatedAmount": 16000
  },
  "chargeTypeAssessment": [
    {
      "taxPeriodFrom": "2020-08-13",
      "taxPeriodTo": "2020-08-14",
      "debtTotalAmount": 300000,
      "taxPeriodCharges": [
        {
          "chargeId": "T5545454554",
          "mainTrans": "22000",
          "mainTransDesc": "",
          "subTrans": "1000",
          "subTransDesc": "",
          "outstandingDebtAmount": 100000,
          "interestStartDate": "2017-03-07",
          "accruedInterestToDate": 15.97,
          "disallowedCharge": true,
          "chargeLocks": {
            "paymentLock": {
              "status": false,
              "reason": ""
            },
            "clearingLock": {
              "status": false,
              "reason": "there is no reason"
            },
            "interestLock": {
              "status": false,
              "reason": "there is no reason"
            },
            "dunningLock": {
              "status": false,
              "reason": "there is no reason"
            },
            "disallowedLock": {
              "status": false,
              "reason": "there is no reason"
            }
          }
        }
      ]
    }
  ]
}

### download eligibility data with errors

POST http://localhost:9218/time-to-pay/self-serve/eligibility
Content-Type: application/json

{
  "idType": "EMPREF",
  "idNumber": "123AAAA",
  "regimeType": "PAYE",
  "returnFinancials": true
}

### Setup Elibility Errors

POST http://localhost:9218/time-to-pay/self-serve/eligibility/paye/123ABCD/errors
Content-Type: application/json

{
  "errors": [
    "Debt is too large",
    "Returns are not up to date",
    "Paye has disallowed charges"
  ]
}

### Retrieve errors

POST http://localhost:9218/time-to-pay/self-serve/eligibility
Content-Type: application/json

{
  "idType": "EMPREF",
  "idNumber": "123ABCD",
  "regimeType": "PAYE",
  "returnFinancials": true
}




