### request affordable quotes with upfront payment
POST http://localhost:9218/debts/time-to-pay/affordability/affordable-quotes
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "channelIdentifier": "eSSTTP",
  "paymentPlanAffordableAmount": 4209,
  "paymentPlanFrequency": "Monthly",
  "paymentPlanMaxLength": 6,
  "paymentPlanMinLength": 1,
  "accruedDebtInterest": 1326,
  "paymentPlanStartDate": "2022-07-08",
  "initialPaymentDate": "2022-06-18",
  "initialPaymentAmount": 1000,
  "debtItemCharges": [
    {
      "outstandingDebtAmount": 14781,
      "mainTrans": "2000",
      "subTrans": "1000",
      "debtItemChargeId": "XW006559808862",
      "interestStartDate": "2022-05-22",
      "debtItemOriginalDueDate": "2022-05-22"
    },
    {
      "outstandingDebtAmount": 3058,
      "mainTrans": "2000",
      "subTrans": "1100",
      "debtItemChargeId": "XW006559808862",
      "interestStartDate": "2022-05-22",
      "debtItemOriginalDueDate": "2022-05-22"
    }
  ],
  "customerPostcodes": [
    {
      "addressPostcode": "BN127ER",
      "postcodeDate": "2022-05-22"
    },
    {
      "addressPostcode": "BN129ER",
      "postcodeDate": "2022-04-30"
    }
  ]
}

### request affordable quotes with no upfront payment
POST http://localhost:9218/debts/time-to-pay/affordability/affordable-quotes
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "channelIdentifier": "eSSTTP",
  "paymentPlanAffordableAmount": 4209,
  "paymentPlanFrequency": "Monthly",
  "paymentPlanMaxLength": 6,
  "paymentPlanMinLength": 1,
  "accruedDebtInterest": 1326,
  "paymentPlanStartDate": "2022-07-08",
  "debtItemCharges": [
    {
      "outstandingDebtAmount": 14781,
      "mainTrans": "2000",
      "subTrans": "1000",
      "debtItemChargeId": "XW006559808862",
      "interestStartDate": "2022-05-22",
      "debtItemOriginalDueDate": "2022-05-22"
    }
  ],
  "customerPostcodes":[
    {
      "postcodeDate":"2022-03-09",
      "addressPostcode":"AB1 3DE"
    }
  ]
}
