### insert eligibility record
POST http://localhost:9218/debts/time-to-pay/eligibility/insert
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "processingDateTime": "test-processingDate",
  "identification": [{
    "idType": "EMPREF",
    "idValue": "test-idValue"
  }],
  "customerPostcodes": [{
    "addressPostcode": "test-postcode",
    "postcodeDate": "2022-01-01"
  }],
  "regimePaymentFrequency": "Monthly",
  "paymentPlanFrequency": "Monthly",
  "paymentPlanMinLength": 1,
  "paymentPlanMaxLength": 6,
  "eligibilityStatus": {
    "eligibilityPass": false
  },
  "eligibilityRules": {
    "hasRlsOnAddress": true,
    "markedAsInsolvent": true,
    "isLessThanMinDebtAllowance": false,
    "isMoreThanMaxDebtAllowance": false,
    "disallowedChargeLockTypes": false,
    "existingTTP": false,
    "chargesOverMaxDebtAge": false,
    "ineligibleChargeTypes": false,
    "missingFiledReturns": false
  },
  "chargeTypeAssessment": [{
    "taxPeriodFrom": "2022-04-27",
    "taxPeriodTo": "2022-04-27",
    "debtTotalAmount": 100,
    "charges": [{
      "chargeType": "test-chargeId",
      "mainType": "test-mainType",
      "chargeReference": "test-chargeReference",
      "mainTrans": "test-mainTrans",
      "subTrans": "test-subTrans",
      "outstandingAmount": 10,
      "interestStartDate": "2022-04-27",
      "dueDate": "2022-04-27",
      "accruedInterest": 1,
      "ineligibleChargeType": false,
      "chargeOverMaxDebtAge": false,
      "locks": [{
        "lockType": "testLockType",
        "lockReason": "testLockReason",
        "disallowedChargeLockType": false
      }]
    }]
  }]
}

### find eligibility record
POST http://localhost:9218/debts/time-to-pay/eligibility
Accept: */*
Cache-Control: no-cache
correlationId: 321dfbae-a62a-41ac-b551-a707dc5d2c5f
Content-Type: Application/Json

{
  "channelIdentifier":"eSSTTP",
  "idType": "test-idType",
  "idValue": "504Error",
  "regimeType": "test-regimeType",
  "returnFinancialAssessment": true
}


### drop eligibility mongo db (remove all records)
DELETE http://localhost:9218/debts/time-to-pay/eligibility/drop
Cache-Control: no-cache
